CREATE TABLE `pubg4j`.`DATA_BEAN` (
  `GUID` BLOB NOT NULL,
  `UNIQUE_ID` VARCHAR(60) NOT NULL,
  `EVENT_ID` VARCHAR(15) NULL DEFAULT NULL,
  `VALUE_DATE` TIMESTAMP NULL DEFAULT NULL,
  `VERSION` INT(11) NULL DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NOT NULL,
  `CREATED_BY` VARCHAR(10) NOT NULL,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
  `UPDATED_BY` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`UNIQUE_ID`));
